version: '3'
services:
  grobid:
    image: lfoppiano/grobid:0.7.2
  scraper:
    image: ghcr.io/opencs-ontology/publication-scraper:main
    container_name: archives_scraper_container
    ports:
      - "8070"
    volumes:
      - ttl_folder:/scraper/output/ttls
      - pdf_folder:/scraper/output/pdfs
    tty: true
  table_and_figures_extraction:
    image: ghcr.io/opencs-ontology/table-and-figure-ie:main
    container_name: table_and_figure_extraction_container
    ports:
      - "8080"
    volumes:
      - ttl_folder:/home/input_ttl_files
      - pdf_folder:/input_pdf_files
    tty: true
  section_and_bibliography_extraction:
    image: ghcr.io/opencs-ontology/section-and-bibliography-ie:main
    container_name: section_and_bibliography_container
    ports:
      - "8090"
    volumes:
      - ttl_folder:/home/input_ttl_files
      - pdf_folder:/input_pdf_files
      - ttl_files_for_every_run:/home/final_ttls_for_every_run
    tty: true
  abstract_embedder:
    image: ghcr.io/opencs-ontology/publication-embeddings:main
    container_name: abstract_embedder_container
    ports:
      - "8060"
    volumes:
      - ttl_files_for_every_run:/home/input_ttl_files
    tty: true

volumes:
  ttl_folder:
  pdf_folder:
  ttl_files_for_every_run:
