version: '3'
services:
  # grobid:
  #   image: lfoppiano/grobid:0.7.2
  # scraper:
  #   image: ghcr.io/opencs-ontology/publication-scraper:main
  #   container_name: archives_scraper_container
  #   ports:
  #     - "8070"
  #   volumes:
  #     - ttl_folder:/scraper/output/ttls
  #     - pdf_folder:/scraper/output/pdfs
  #   tty: true
  # table_and_figures_extraction:
  #   image: ghcr.io/opencs-ontology/table-and-figure-ie:main
  #   container_name: table_and_figure_extraction_container
  #   ports:
  #     - "8080"
  #   volumes:
  #     - ttl_folder:/home/input_ttl_files
  #     - pdf_folder:/input_pdf_files
  #     - ttl_files_for_every_run:/home/final_ttls_for_every_run
  #   tty: true
  # section_and_bibliography_extraction:
  #   image: ghcr.io/opencs-ontology/section-and-bibliography-ie:main
  #   container_name: section_and_bibliography_container
  #   ports:
  #     - "8090"
  #   volumes:
  #     - ttl_folder:/home/input_ttl_files
  #     - pdf_folder:/input_pdf_files
  #   tty: true
  # abstract_embedder:
  #   image: ghcr.io/opencs-ontology/publication-embeddings:main
  #   container_name: abstract_embedder_container
  #   ports:
  #     - "8060"
  #   volumes:
  #     - ttl_files_for_every_run:/home/input_ttl_files
  #     - concepts_embeddings:/home/output_concepts_json
  #     - embedded_ttls:/home/output_ttl_files
  #   tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch_container
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  topical_classifier_es:
    image: ghcr.io/opencs-ontology/topical-classifier-elastic:main
    container_name: topical_classifier_container
    network_mode: host
    ports:
      - "8050"
    volumes:
      - embedded_ttls:/home/output
      - concepts_embeddings:/home/concepts_json
    tty: true

volumes:
  ttl_folder:
  pdf_folder:
  ttl_files_for_every_run:
  concepts_embeddings:
  embedded_ttls:
